#!/usr/bin/env bash
# Auto-generated by scheduled task goj-3pm-signin-driver-sheets.
# Triggers the existing job in goj_daily_scheduler.py so it runs from the host
# (the Cowork sandbox cannot reach api.telegram.org).
set -e

LOG="$HOME/Desktop/REX/logs/goj_scheduler.log"
mkdir -p "$HOME/Desktop/REX/logs"

REX_DIR="$HOME/Desktop/REX"
DAILY_DIR="$HOME/Documents/goj files/dashboard"

# Pick a python — prefer the REX venv if present
VENV_PY="$REX_DIR/.venv/bin/python3"
if [ -x "$VENV_PY" ]; then
    PY="$VENV_PY"
else
    PY="$(command -v python3)"
fi

echo "──────────────────────────────────────────────────────────────"
echo "  GOJ — signin_driver_sheets — $(date '+%Y-%m-%d %H:%M:%S')"
echo "  Python: $PY"
echo "──────────────────────────────────────────────────────────────"

cd "$REX_DIR"
"$PY" "$REX_DIR/goj_daily_scheduler.py" --job signin_driver_sheets 2>&1 | tee -a "$LOG"
EXIT_CODE=${PIPESTATUS[0]}

echo ""
echo "──────────────────────────────────────────────────────────────"
if [ "$EXIT_CODE" -eq 0 ]; then
    echo "  ✅ Done — exit $EXIT_CODE"
else
    echo "  ❌ Failed — exit $EXIT_CODE  (see $LOG)"
fi
echo "──────────────────────────────────────────────────────────────"
echo ""
echo "This window will close in 6 seconds…"
sleep 6
osascript -e 'tell application "Terminal" to close (every window whose name contains "_run_signin_driver_now")' >/dev/null 2>&1 || true
exit "$EXIT_CODE"
