#!/bin/bash
echo "=== BBG DIAGNOSTIC ==="
echo ""
echo "1) Server on 4173:"
curl -s -o /dev/null -w "HTTP %{http_code}" http://localhost:4173 2>/dev/null || echo "NO RESPONSE"
echo ""
echo ""
echo "2) PID file:"
cat ~/Downloads/bbg-app/serve.pid 2>/dev/null || echo "no PID file"
echo ""
echo "3) Process running?"
ps aux | grep "vite.*4173\|vite.*preview" | grep -v grep || echo "NOT RUNNING"
echo ""
echo "4) Tunnel config bbg entry:"
grep -A2 "bbg" ~/.cloudflared/hermestigerclaw.yml 2>/dev/null || echo "not found in config"
echo ""
echo "=== END ==="
read -n 1 -p "Press any key..."
