#!/bin/bash
# CC_telegram_fix — Hermes Telegram Bot Diagnostic + Fix
# Gold Health Systems · Generated by Claude
set -euo pipefail

TIMESTAMP=$(date +%Y%m%d_%H%M%S)
LOG="$HOME/Desktop/REX/logs/CC_telegram_fix_${TIMESTAMP}.log"
mkdir -p "$HOME/Desktop/REX/logs"
exec > >(tee "$LOG") 2>&1

echo "============================================================"
echo " HERMES TELEGRAM BOT DIAGNOSTIC + FIX"
echo " $(date)"
echo "============================================================"
echo ""

# ── 1. GATEWAY HEALTH ──────────────────────────────────────────
echo "=== [1] GATEWAY HEALTH ==="
for PORT_INFO in "3002:Hermes Cloud GW" "8000:REX FastAPI" "8080:GOJ Dashboard"; do
  PORT="${PORT_INFO%%:*}"
  NAME="${PORT_INFO##*:}"
  RESULT=$(curl -s --max-time 3 "http://localhost:${PORT}/health" 2>/dev/null || echo "UNREACHABLE")
  echo "  ${NAME} (port ${PORT}): ${RESULT}"
done
echo ""

# ── 2. LAUNCHAGENT STATUS ──────────────────────────────────────
echo "=== [2] LAUNCHAGENT STATUS ==="
launchctl list 2>/dev/null | grep -E "hermes|rex|goj|rexxie|goldhealth|tigerclaw" || echo "  (none matched)"
echo ""

echo "=== [2b] ALL HERMES/REX PLISTS IN LaunchAgents ==="
ls ~/Library/LaunchAgents/ | grep -E "hermes|rex|goj|rexxie|goldhealth|tigerclaw" || echo "  (none found)"
echo ""

# ── 3. HERMES GATEWAY LOG ──────────────────────────────────────
echo "=== [3] HERMES GATEWAY LOG (last 80 lines) ==="
LOG_FILE="$HOME/.hermes/profiles/cloud/logs/gateway.log"
if [ -f "$LOG_FILE" ]; then
  tail -80 "$LOG_FILE"
else
  echo "  Log file not found: $LOG_FILE"
  # Try to find any gateway log
  find "$HOME/.hermes" -name "*.log" -newer /tmp 2>/dev/null | head -5 | while read f; do
    echo "  Found log: $f"
    tail -20 "$f"
  done
fi
echo ""

# ── 4. BOT TOKEN DISCOVERY ─────────────────────────────────────
echo "=== [4] BOT TOKEN DISCOVERY ==="

CONFIG_FILE="$HOME/.hermes/profiles/cloud/config.yaml"
ENV_FILE="$HOME/.hermes/profiles/cloud/.env"

if [ -f "$CONFIG_FILE" ]; then
  echo "  --- config.yaml (telegram-related lines) ---"
  grep -i "telegram\|bot_token\|TELEGRAM\|bot.*token\|token.*bot" "$CONFIG_FILE" 2>/dev/null || echo "  (no telegram entries in config.yaml)"
else
  echo "  config.yaml NOT FOUND at $CONFIG_FILE"
fi

if [ -f "$ENV_FILE" ]; then
  echo "  --- .env (telegram-related lines) ---"
  grep -i "telegram\|bot_token\|TELEGRAM" "$ENV_FILE" 2>/dev/null || echo "  (no telegram entries in .env)"
else
  echo "  .env NOT FOUND at $ENV_FILE"
fi

# Also check REX .env
REX_ENV="$HOME/Desktop/REX/.env"
if [ -f "$REX_ENV" ]; then
  echo "  --- REX/.env (telegram-related lines) ---"
  grep -i "telegram\|bot_token\|TELEGRAM" "$REX_ENV" 2>/dev/null || echo "  (no telegram entries in REX/.env)"
fi

# Check n8n config
N8N_ENV="$HOME/.n8n/.env"
if [ -f "$N8N_ENV" ]; then
  echo "  --- n8n .env (telegram) ---"
  grep -i "telegram\|bot" "$N8N_ENV" 2>/dev/null || echo "  (no telegram in n8n)"
fi
echo ""

# ── 5. EXTRACT AND TEST BOT TOKEN ─────────────────────────────
echo "=== [5] TESTING BOT TOKEN VIA TELEGRAM API ==="

# Extract token from config or env
BOT_TOKEN=""
if [ -f "$CONFIG_FILE" ]; then
  BOT_TOKEN=$(grep -i "bot_token\|telegram.*token\|token.*bot" "$CONFIG_FILE" 2>/dev/null | grep -oP '(?<=:\s)[0-9]+:[A-Za-z0-9_-]+' | head -1)
fi
if [ -z "$BOT_TOKEN" ] && [ -f "$ENV_FILE" ]; then
  BOT_TOKEN=$(grep -iE "TELEGRAM_BOT_TOKEN|BOT_TOKEN|HERMES_BOT_TOKEN" "$ENV_FILE" 2>/dev/null | cut -d'=' -f2 | tr -d '"' | tr -d "'" | head -1)
fi
if [ -z "$BOT_TOKEN" ] && [ -f "$REX_ENV" ]; then
  BOT_TOKEN=$(grep -iE "TELEGRAM_BOT_TOKEN|BOT_TOKEN|HERMES_BOT_TOKEN" "$REX_ENV" 2>/dev/null | cut -d'=' -f2 | tr -d '"' | tr -d "'" | head -1)
fi

if [ -n "$BOT_TOKEN" ]; then
  TOKEN_PREVIEW="${BOT_TOKEN:0:10}...${BOT_TOKEN: -6}"
  echo "  Token found (masked): $TOKEN_PREVIEW"
  echo "  Testing with Telegram API..."
  TG_RESULT=$(curl -s --max-time 10 "https://api.telegram.org/bot${BOT_TOKEN}/getMe" 2>/dev/null)
  echo "  Telegram API response: $TG_RESULT"
  
  if echo "$TG_RESULT" | grep -q '"ok":true'; then
    echo "  ✅ Bot token is VALID"
    BOT_NAME=$(echo "$TG_RESULT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d['result'].get('username','unknown'))" 2>/dev/null || echo "unknown")
    echo "  Bot username: @$BOT_NAME"
  elif echo "$TG_RESULT" | grep -q '"ok":false'; then
    echo "  ❌ Bot token is INVALID or REVOKED"
    echo "  Full response: $TG_RESULT"
  else
    echo "  ⚠️  No response from Telegram API (network issue?)"
  fi
else
  echo "  ⚠️  Could not extract bot token from config.yaml or .env"
  echo "  Checked: $CONFIG_FILE, $ENV_FILE, $REX_ENV"
fi
echo ""

# ── 6. FIND ALL BOT TOKENS ─────────────────────────────────────
echo "=== [6] ALL BOT TOKENS IN CONFIG FILES ==="
# Search more broadly for Telegram bot tokens (format: NUMBER:STRING)
echo "  Scanning for Telegram token patterns..."
grep -rh --include="*.yaml" --include="*.yml" --include="*.env" --include="*.json" --include="*.py" \
  -E "[0-9]{8,12}:[A-Za-z0-9_-]{35,}" \
  "$HOME/.hermes/profiles/cloud/" "$HOME/Desktop/REX/" 2>/dev/null | \
  sed 's/\([0-9]\{8,12\}:[A-Za-z0-9_-]\{6\}\)[A-Za-z0-9_-]*/\1[MASKED]/g' | head -20 || echo "  none found"
echo ""

# ── 7. REXXIE GOLD HEALTH SERVICE ─────────────────────────────
echo "=== [7] REXXIE GOLD HEALTH SERVICE ==="
echo "  LaunchAgent files matching 'rexxie' or 'goldhealth':"
find ~/Library/LaunchAgents/ -name "*rexxie*" -o -name "*goldhealth*" -o -name "*gold*health*" 2>/dev/null | grep -v "com.hermes.rexxie-bot" || echo "  none found (excluding zombie)"

echo "  Checking if any rexxie process is running:"
pgrep -la -i rexxie 2>/dev/null || echo "  No rexxie process found"
ps aux | grep -i "rexxie\|goldhealth" | grep -v grep || echo "  No rexxie/goldhealth process in ps"
echo ""

# ── 8. WORKSPACE PLISTS (potential interference) ───────────────
echo "=== [8] WORKSPACE LAUNCHAGENTS ==="
launchctl list 2>/dev/null | grep -i workspace || echo "  (none)"
ls ~/Library/LaunchAgents/ | grep -i workspace 2>/dev/null || echo "  (no workspace plists)"
echo ""

# ── 9. CRASHED PROCESSES ──────────────────────────────────────
echo "=== [9] RECENT CRASH REPORTS (last 2 hours) ==="
find ~/Library/Logs/DiagnosticReports -name "*hermes*" -o -name "*rexxie*" -o -name "*rex*" 2>/dev/null | \
  xargs ls -lt 2>/dev/null | head -10 || echo "  No recent crash reports found"
echo ""

# ── 10. PLIST CONTENTS FOR HERMES CLOUD GW ────────────────────
echo "=== [10] HERMES CLOUD GW PLIST ==="
PLIST_CLOUD="$HOME/Library/LaunchAgents/ai.hermes.gateway-cloud.plist"
if [ -f "$PLIST_CLOUD" ]; then
  cat "$PLIST_CLOUD"
else
  echo "  PLIST NOT FOUND: $PLIST_CLOUD"
fi
echo ""

# ── 11. ALL BOT-RELATED PLIST CONTENTS ────────────────────────
echo "=== [11] ALL HERMES/REX/GOJ PLIST DETAILS ==="
for PLIST in ~/Library/LaunchAgents/ai.hermes.*.plist ~/Library/LaunchAgents/com.rex.*.plist ~/Library/LaunchAgents/com.goj.*.plist; do
  if [ -f "$PLIST" ]; then
    echo "  --- $PLIST ---"
    # Show label, program args, disabled status
    grep -A1 -E "<key>(Label|ProgramArguments|Disabled|EnvironmentVariables)</key>" "$PLIST" | head -30
    echo ""
  fi
done
echo ""

# ── 12. FIX: ATTEMPT HERMES CLOUD GW RESTART ──────────────────
echo "=== [12] ATTEMPTING HERMES CLOUD GW RESTART ==="
PLIST_CLOUD="$HOME/Library/LaunchAgents/ai.hermes.gateway-cloud.plist"
if [ -f "$PLIST_CLOUD" ]; then
  echo "  Unloading..."
  launchctl unload "$PLIST_CLOUD" 2>/dev/null || echo "  (was not loaded)"
  echo "  Killing any lingering hermes gateway process..."
  pkill -f "hermes_cli.main.*gateway" 2>/dev/null || echo "  (no process to kill)"
  echo "  Sleeping 10s..."
  sleep 10
  echo "  Loading..."
  launchctl load "$PLIST_CLOUD"
  sleep 6
  echo "  Health check:"
  curl -s --max-time 5 "http://localhost:3002/health" 2>/dev/null || echo "  STILL DOWN after restart"
else
  echo "  SKIPPED — plist not found"
fi
echo ""

# ── 13. FIX: DISABLE WORKSPACE INTERFERENCE ───────────────────
echo "=== [13] DISABLE WORKSPACE INTERFERENCE ==="
for WS_PLIST in "$HOME/Library/LaunchAgents/com.hermes.cloud-workspace.plist" "$HOME/Library/LaunchAgents/com.hermes.workspace.plist"; do
  if [ -f "$WS_PLIST" ]; then
    echo "  Found: $WS_PLIST — disabling..."
    launchctl unload "$WS_PLIST" 2>/dev/null || echo "  (was not loaded)"
    echo "  ✅ Unloaded $WS_PLIST"
  fi
done
echo ""

# ── 14. POST-FIX HEALTH CHECK ─────────────────────────────────
echo "=== [14] POST-FIX HEALTH CHECK ==="
sleep 3
for PORT_INFO in "3002:Hermes Cloud GW" "8000:REX FastAPI" "8080:GOJ Dashboard"; do
  PORT="${PORT_INFO%%:*}"
  NAME="${PORT_INFO##*:}"
  RESULT=$(curl -s --max-time 3 "http://localhost:${PORT}/health" 2>/dev/null || echo "❌ UNREACHABLE")
  echo "  ${NAME} (port ${PORT}): ${RESULT}"
done
echo ""

echo "=== [15] POST-FIX LAUNCHAGENT STATUS ==="
launchctl list 2>/dev/null | grep -E "hermes|rex|goj|rexxie|goldhealth|tigerclaw" || echo "  (none matched)"
echo ""

echo "============================================================"
echo " DIAGNOSTIC COMPLETE — $(date)"
echo " Log saved to: $LOG"
echo "============================================================"

# Write brief summary report
SUMMARY="$HOME/Desktop/REX/CC_telegram_fix_${TIMESTAMP}.txt"
{
  echo "HERMES TELEGRAM BOT DIAGNOSTIC REPORT"
  echo "Generated: $(date)"
  echo "Full log: $LOG"
  echo ""
  echo "GATEWAY STATUS (post-fix):"
  for PORT_INFO in "3002:Hermes Cloud GW" "8000:REX FastAPI" "8080:GOJ Dashboard"; do
    PORT="${PORT_INFO%%:*}"
    NAME="${PORT_INFO##*:}"
    RESULT=$(curl -s --max-time 3 "http://localhost:${PORT}/health" 2>/dev/null || echo "UNREACHABLE")
    echo "  $NAME: $RESULT"
  done
  echo ""
  echo "LAUNCHCTL STATUS:"
  launchctl list 2>/dev/null | grep -E "hermes|rex|goj|rexxie|goldhealth|tigerclaw" || echo "  (none)"
  echo ""
  echo "See full log for token test results, crash reports, and fix actions."
} > "$SUMMARY"
echo ""
echo "Summary written to: $SUMMARY"
