#!/usr/bin/env python3
"""
CC_wiki_validator.py — Scans Obsidian vault for contradictions, broken links, and stale builds.
Runs as cron job. Updates Contradictions.md in the wiki.
"""

import os, re, json, subprocess, sys
from datetime import datetime, timedelta
from pathlib import Path

VAULT = os.path.expanduser("~/GHS-Vault")  # TCC-safe mirror
WIKI = f"{VAULT}/Cloud Backups/claude-wiki"
CONTRADICTIONS_FILE = f"{WIKI}/concepts/Contradictions.md"
API_BASE = "https://127.0.0.1:27124"
API_KEY = "50be2c0212680e76a787968f6b8e28fe6ad418201ebb300748b72e271f37805a"

def find_all_md_files(root):
    return list(Path(root).rglob("*.md"))

def check_broken_links():
    """Find [[wikilinks]] that don't resolve to any file."""
    all_files = {f.stem for f in find_all_md_files(VAULT)}
    all_files.update({f.name.replace('.md','') for f in find_all_md_files(VAULT)})
    broken = []
    
    for md_file in find_all_md_files(VAULT):
        try:
            content = md_file.read_text(errors='ignore')
        except (FileNotFoundError, PermissionError, OSError):
            continue
        links = re.findall(r'\[\[([^\]|#]+)', content)
        for link in links:
            clean = link.strip().split('|')[0].split('#')[0]
            if clean not in all_files and not clean.startswith('http'):
                broken.append(f"  - {md_file.relative_to(VAULT)} → [[{link}]]")
    
    return broken[:20]  # Cap at 20

def check_stale_builds():
    """Find build/REX files with stale references."""
    stale = []
    rex_dir = os.path.expanduser("~/Desktop/REX")
    
    # Check for scripts referenced in cron but missing on disk
    jobs_file = os.path.expanduser("~/.hermes/profiles/cloud/cron/jobs.json")
    if os.path.exists(jobs_file):
        with open(jobs_file) as f:
            data = json.load(f)
        for job in data.get('jobs', []):
            script = job.get('script', '')
            if script:
                script_path = os.path.expanduser(f"~/.hermes/profiles/cloud/scripts/{script}")
                if not os.path.exists(script_path):
                    stale.append(f"  - Cron '{job.get('name','?')}' → missing script: {script}")
    
    return stale

def check_contradictions():
    """Cross-reference key facts across vault files and flag conflicts."""
    contradictions = []
    
    # Check if REST API port is consistent
    pm = f"{VAULT}/Hermes Perpetual Memory.md"
    rest_config = f"{VAULT}/.obsidian/plugins/obsidian-local-rest-api/data.json"
    
    if os.path.exists(rest_config):
        try:
            with open(rest_config) as f:
                config = json.load(f)
            actual_port = config.get('port', 'unknown')
            
            if os.path.exists(pm):
                pm_content = open(pm).read()
                pm_ports = re.findall(r'2712[45]', pm_content)
                if pm_ports:
                    if str(actual_port) not in pm_ports:
                        contradictions.append(f"  - Port mismatch: REST API on {actual_port}, PM says {'/'.join(pm_ports)}")
        except:
            pass
    
    # Check model names across configs
    cloud_config = os.path.expanduser("~/.hermes/profiles/cloud/config.yaml")
    rexxie_config = os.path.expanduser("~/.hermes/profiles/rexxie_personal/config.yaml")
    
    return contradictions

def update_obsidian(content):
    """Push to Obsidian via REST API."""
    import requests
    try:
        r = requests.put(
            f"{API_BASE}/vault/Cloud%20Backups/claude-wiki/concepts/Contradictions.md",
            headers={"Authorization": f"Bearer {API_KEY}"},
            data=content.encode('utf-8'),
            verify=False,
            timeout=10
        )
        return r.status_code in (200, 201, 204)
    except:
        return False

def main():
    print("=== Wiki Validator —", datetime.now().isoformat(), "===")
    
    # Run checks
    broken = check_broken_links()
    stale = check_stale_builds()
    contradictions = check_contradictions()
    
    # Build report
    report = []
    report.append("# Contradictions & Broken Builds")
    report.append(f"\n> Last scan: {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}")
    report.append(f"> Auto-generated by CC_wiki_validator.py\n")
    
    if contradictions:
        report.append("## 🔴 Contradictions\n")
        for c in contradictions:
            report.append(c)
    else:
        report.append("## 🔴 Contradictions\n\n✅ None detected.\n")
    
    if broken:
        report.append(f"\n## 🟡 Broken Links ({len(broken)})\n")
        for b in broken:
            report.append(b)
    else:
        report.append("\n## 🟡 Broken Links\n\n✅ All wikilinks resolve.\n")
    
    if stale:
        report.append(f"\n## 🟠 Stale/Broken Builds ({len(stale)})\n")
        for s in stale:
            report.append(s)
    else:
        report.append("\n## 🟠 Stale/Broken Builds\n\n✅ All build references valid.\n")
    
    report.append(f"\n---\n*Scan completed: {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}*")
    
    content = '\n'.join(report)
    
    # Push to Obsidian FIRST (API may clobber local file)
    if update_obsidian(content):
        print("Pushed to Obsidian ✅")
    else:
        print("Obsidian push failed — API may be unreachable")
    
    # Write locally AFTER API (API PUT returns 204 but overwrites local file with stale GET)
    os.makedirs(os.path.dirname(CONTRADICTIONS_FILE), exist_ok=True)
    with open(CONTRADICTIONS_FILE, 'w') as f:
        f.write(content)
    print(f"Written locally: {CONTRADICTIONS_FILE}")
    
    # Summary
    total_issues = len(contradictions) + len(broken) + len(stale)
    print(f"\nTotal issues: {total_issues} ({len(contradictions)} contradictions, {len(broken)} broken links, {len(stale)} stale builds)")

if __name__ == "__main__":
    import urllib3
    urllib3.disable_warnings()
    main()
