#!/usr/bin/env bash
# GOJ 3PM Sheet Sender — Wednesday May 27, 2026 sheets
# Generated by Rexxie scheduled task (3 PM Tue May 26, 2026).
# Sandbox could not reach api.telegram.org — double-click this on your Mac to send.

set -e
REX_DIR="$HOME/Desktop/REX"
CONFIG="$REX_DIR/rex_rexxie_telegram_config.json"

TOKEN=$(python3 -c "import json; d=json.load(open('$CONFIG')); print(d['bot_token'])")
CHAT_ID=$(python3 -c "import json; d=json.load(open('$CONFIG')); print(d['owner_chat_id'])")

echo "Sending GOJ Wednesday May 27 sheets to Telegram..."

# Summary message
python3 - "$TOKEN" "$CHAT_ID" <<'PYEOF'
import sys, json, urllib.request, urllib.parse
token, chat_id = sys.argv[1], sys.argv[2]
msg = (
    "\U0001F697 <b>GOJ Sheets for Wednesday, May 27, 2026</b>\n\n"
    "\U0001F465 Clients expected: 166\n"
    "  Shift 1: 90 | Shift 2: 76\n"
    "\U0001F68C Drivers on duty: 7\n\n"
    "\U0001F4CB Sign-in sheet and driver lists attached below."
)
data = urllib.parse.urlencode({
    "chat_id": chat_id, "text": msg, "parse_mode": "HTML"
}).encode()
r = urllib.request.urlopen(urllib.request.Request(
    f"https://api.telegram.org/bot{token}/sendMessage", data=data))
print("  Summary:", "OK" if json.loads(r.read())["ok"] else "FAIL")
PYEOF

# Send each PDF
for PDF in \
    "$REX_DIR/GOJ_W_S1_Wednesday_signin.pdf" \
    "$REX_DIR/GOJ_W_S2_Wednesday_signin.pdf" \
    "$REX_DIR/GOJ_W_S1_Wednesday_drivers.pdf" \
    "$REX_DIR/GOJ_W_S2_Wednesday_drivers.pdf"; do

    if [ -f "$PDF" ]; then
        BASENAME=$(basename "$PDF")
        echo "  Sending $BASENAME..."
        python3 - "$PDF" "$TOKEN" "$CHAT_ID" <<'PYEOF'
import sys, json, urllib.request

pdf_path, token, chat_id = sys.argv[1], sys.argv[2], sys.argv[3]
boundary = "----FormBoundary7MA4YWxkTrZu0gW"
with open(pdf_path, "rb") as f:
    pdf_data = f.read()

basename = pdf_path.split("/")[-1]
body = (
    f"--{boundary}\r\n"
    f'Content-Disposition: form-data; name="chat_id"\r\n\r\n{chat_id}\r\n'
    f"--{boundary}\r\n"
    f'Content-Disposition: form-data; name="document"; filename="{basename}"\r\n'
    f"Content-Type: application/pdf\r\n\r\n"
).encode() + pdf_data + f"\r\n--{boundary}--\r\n".encode()

req = urllib.request.Request(
    f"https://api.telegram.org/bot{token}/sendDocument",
    data=body,
    headers={"Content-Type": f"multipart/form-data; boundary={boundary}"}
)
r = urllib.request.urlopen(req)
result = json.loads(r.read())
print(f"    {'OK' if result.get('ok') else 'FAIL'} {basename}")
PYEOF
    else
        echo "  Missing: $PDF"
    fi
done

echo ""
echo "Done. All sheets sent to Telegram."
read -n 1 -s -r -p "Press any key to close this window..."
