#!/usr/bin/env bash
# GOJ 3PM Sheet Sender — Wednesday April 29, 2026 sheets
# Generated by Rexxie scheduled task at 3 PM Tue Apr 28 2026.
set -e

REX_DIR="$HOME/Desktop/REX"
OUT_DIR="$HOME/Documents/goj files/output_docs"
LOG="$REX_DIR/.send_log_wed_apr29.txt"

exec > >(tee -a "$LOG") 2>&1
echo "==== Run at $(date) ===="

CONFIG="$REX_DIR/rex_rexxie_telegram_config.json"
TOKEN=$(python3 -c "import json; print(json.load(open('$CONFIG'))['bot_token'])")
CHAT_ID=$(python3 -c "import json; print(json.load(open('$CONFIG'))['owner_chat_id'])")

echo "Sending GOJ Wed Apr 29 sheets to Telegram chat $CHAT_ID..."

# 1) Send summary
python3 - "$TOKEN" "$CHAT_ID" <<'PYEOF'
import sys, json, urllib.request, urllib.parse
token, chat_id = sys.argv[1], sys.argv[2]
msg = (
    "\U0001F697 <b>GOJ Sheets for Wednesday, 2026-04-29</b>\n\n"
    "\U0001F465 Clients expected: <b>166</b>\n"
    "  Shift 1: 76 | Shift 2: 90\n"
    "\U0001F68C Drivers on duty: <b>7</b>\n"
    "  (Alisher, Andrey, Gena, Oleg, Ravil, Vadik, Valera)\n\n"
    "\U0001F4CB Sign-in sheets and driver lists attached below."
)
data = urllib.parse.urlencode({"chat_id": chat_id, "text": msg, "parse_mode": "HTML"}).encode()
r = urllib.request.urlopen(urllib.request.Request(
    f"https://api.telegram.org/bot{token}/sendMessage", data=data), timeout=20)
print("summary:", json.loads(r.read()).get("ok"))
PYEOF

# 2) Send each PDF
for PDF in \
    "$OUT_DIR/GOJ_W_S1_Wednesday_signin.pdf" \
    "$OUT_DIR/GOJ_W_S2_Wednesday_signin.pdf" \
    "$OUT_DIR/GOJ_W_S1_Wednesday_drivers.pdf" \
    "$OUT_DIR/GOJ_W_S2_Wednesday_drivers.pdf"
do
    if [ -f "$PDF" ]; then
        echo "  Sending $(basename "$PDF") ..."
        python3 - "$PDF" "$TOKEN" "$CHAT_ID" <<'PYEOF'
import sys, json, urllib.request
pdf_path, token, chat_id = sys.argv[1], sys.argv[2], sys.argv[3]
boundary = "----GOJBoundary29Apr"
basename = pdf_path.split("/")[-1]
with open(pdf_path, "rb") as f:
    pdf = f.read()
body = (
    f"--{boundary}\r\n"
    f'Content-Disposition: form-data; name="chat_id"\r\n\r\n{chat_id}\r\n'
    f"--{boundary}\r\n"
    f'Content-Disposition: form-data; name="document"; filename="{basename}"\r\n'
    f"Content-Type: application/pdf\r\n\r\n"
).encode() + pdf + f"\r\n--{boundary}--\r\n".encode()
req = urllib.request.Request(
    f"https://api.telegram.org/bot{token}/sendDocument",
    data=body,
    headers={"Content-Type": f"multipart/form-data; boundary={boundary}",
             "Content-Length": str(len(body))})
r = urllib.request.urlopen(req, timeout=60)
result = json.loads(r.read())
print(f"  {'OK' if result.get('ok') else 'FAIL'} {basename}")
PYEOF
    else
        echo "  WARN: missing $PDF"
    fi
done

echo "Done."
