#!/usr/bin/env python3
"""
GOJ Sign-In & Driver Sheets — 3 PM Send to Kato via Telegram
Auto-generated by REX scheduled task for Monday, April 20, 2026
"""
import json, urllib.request, urllib.parse, sys
from pathlib import Path

HERE    = Path(__file__).parent  # ~/Desktop/REX/
OUT     = HERE  # PDFs were copied directly into REX folder

cfg     = json.load(open(HERE / "rex_rexxie_telegram_config.json"))
TOKEN   = cfg["bot_token"]
CHAT_ID = cfg["owner_chat_id"]

def tg_send_message(text):
    url  = f"https://api.telegram.org/bot{TOKEN}/sendMessage"
    data = urllib.parse.urlencode({
        "chat_id": CHAT_ID, "text": text, "parse_mode": "HTML"
    }).encode()
    with urllib.request.urlopen(
        urllib.request.Request(url, data=data), timeout=15
    ) as r:
        return json.loads(r.read())

def tg_send_document(path, caption=""):
    boundary = "----GOJBoundary"
    def part(name, value, ctype=None, fname=None):
        h = f'--{boundary}\r\nContent-Disposition: form-data; name="{name}"'
        if fname: h += f'; filename="{fname}"'
        h += "\r\n"
        if ctype: h += f"Content-Type: {ctype}\r\n"
        h += "\r\n"
        return h.encode() + (value if isinstance(value, bytes) else value.encode()) + b"\r\n"
    body = b""
    body += part("chat_id", str(CHAT_ID))
    body += part("caption", caption)
    body += part("parse_mode", "HTML")
    with open(path, "rb") as f:
        body += part("document", f.read(), "application/pdf", path.name)
    body += f"--{boundary}--\r\n".encode()
    url = f"https://api.telegram.org/bot{TOKEN}/sendDocument"
    req = urllib.request.Request(url, data=body, method="POST")
    req.add_header("Content-Type", f"multipart/form-data; boundary={boundary}")
    req.add_header("Content-Length", str(len(body)))
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read())

# --- Files (freshly generated Apr 17 for Mon Apr 20) ---
signin_s1 = OUT / "GOJ_M_S1_Monday_signin.pdf"
driver_s1 = OUT / "GOJ_M_S1_Monday_drivers.pdf"
driver_s2 = OUT / "GOJ_M_S2_Monday_drivers.pdf"

TEMPLATE_SIGNIN = HERE / "TEMPLATE_signin.pdf"
TEMPLATE_DRIVER = HERE / "TEMPLATE_driver.pdf"

# Check which files actually exist
all_missing = not signin_s1.exists() and not driver_s1.exists() and not driver_s2.exists()

# --- Summary message ---
if all_missing:
    summary = (
        "🚗 <b>GOJ Sheets for Monday, April 20, 2026</b>\n\n"
        "⚠️ Could not generate populated sheets — sending blank templates instead.\n\n"
        "📋 Blank sign-in sheet and driver template attached below."
    )
else:
    summary = (
        "🚗 <b>GOJ Sheets for Monday, April 20, 2026</b>\n\n"
        "👥 Clients expected: 150\n"
        "  Shift 1: 97 | Shift 2: 53\n"
        "🚌 Drivers on duty: 7\n\n"
        "📋 Sign-in sheet and driver lists attached below."
    )

print("Sending summary message...")
r = tg_send_message(summary)
print(f"  → message_id: {r.get('result', {}).get('message_id', '?')}")

if all_missing:
    for label, path in [
        ("Sign-In Sheet — BLANK TEMPLATE", TEMPLATE_SIGNIN),
        ("Driver Route Sheet — BLANK TEMPLATE", TEMPLATE_DRIVER),
    ]:
        if path.exists():
            print(f"Sending template: {path.name}")
            r = tg_send_document(path, f"📄 {label}")
            print(f"  → {'✓ OK' if r.get('ok') else '✗ FAILED: ' + str(r)}")
        else:
            print(f"⚠️ Template not found: {path}")
else:
    docs = []
    if signin_s1.exists():
        docs.append(("Sign-In Sheet — Monday Apr 20", signin_s1))
    if driver_s1.exists():
        docs.append(("Driver Route List Shift 1 — Monday Apr 20", driver_s1))
    if driver_s2.exists():
        docs.append(("Driver Route List Shift 2 — Monday Apr 20", driver_s2))

    for label, path in docs:
        print(f"Sending: {path.name}")
        r = tg_send_document(path, f"📄 {label}")
        print(f"  → {'✓ OK' if r.get('ok') else '✗ FAILED: ' + str(r)}")

print("\n✅ Done.")
