#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════════════════════
#  REX — Cloudflare Tunnel Setup
#  Exposes your REX dashboard at goldhealthsys.com via Cloudflare Tunnel.
#
#  What this does:
#    1. Downloads cloudflared (the Cloudflare Tunnel client) for your Mac
#    2. Walks you through a one-time Cloudflare login (opens your browser)
#    3. Creates a named tunnel "rex-dashboard"
#    4. Writes the tunnel config pointing localhost:8000 → goldhealthsys.com
#    5. Adds the DNS record on Cloudflare automatically
#    6. Installs a launchd daemon so the tunnel starts on every boot
#
#  Prerequisites (you need these before running):
#    ✅  goldhealthsys.com must be added to your Cloudflare account
#        (go to dash.cloudflare.com → Add site → follow the steps)
#    ✅  REX must be running on localhost:8000 when you want the site live
#
#  Run once:
#    bash ~/Desktop/REX/setup_cloudflare_tunnel.sh
# ══════════════════════════════════════════════════════════════════════════════

set -e

BLUE='\033[0;34m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
RED='\033[0;31m'; BOLD='\033[1m'; NC='\033[0m'

TUNNEL_NAME="rex-dashboard"
DOMAIN="goldhealthsys.com"
LOCAL_URL="http://localhost:8000"
CF_DIR="$HOME/.cloudflared"
CONFIG_FILE="$CF_DIR/rex-dashboard-config.yml"
PLIST_NAME="com.rex.cloudflare-tunnel"
PLIST_DST="$HOME/Library/LaunchAgents/$PLIST_NAME.plist"
REX_DIR="$HOME/Desktop/REX"
LOG_DIR="$REX_DIR/logs"

mkdir -p "$CF_DIR" "$LOG_DIR"

echo ""
echo -e "${BOLD}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║   REX Cloudflare Tunnel Setup                   ║${NC}"
echo -e "${BOLD}║   goldhealthsys.com → localhost:8000            ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════════════╝${NC}"
echo ""

# ── Step 1: Download cloudflared ──────────────────────────────────────────────
if command -v cloudflared &>/dev/null; then
    echo -e "${GREEN}✅  cloudflared already installed: $(cloudflared --version 2>&1 | head -1)${NC}"
else
    echo -e "${BLUE}📥  Downloading cloudflared...${NC}"

    ARCH=$(uname -m)
    if [[ "$ARCH" == "arm64" ]]; then
        CF_URL="https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-darwin-arm64.tgz"
    else
        CF_URL="https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-darwin-amd64.tgz"
    fi

    TMP_DIR=$(mktemp -d)
    curl -L --progress-bar "$CF_URL" -o "$TMP_DIR/cloudflared.tgz"
    tar -xzf "$TMP_DIR/cloudflared.tgz" -C "$TMP_DIR"
    sudo mv "$TMP_DIR/cloudflared" /usr/local/bin/cloudflared
    sudo chmod +x /usr/local/bin/cloudflared
    rm -rf "$TMP_DIR"

    echo -e "${GREEN}✅  cloudflared installed: $(cloudflared --version 2>&1 | head -1)${NC}"
fi

# ── Step 2: Cloudflare Login (one-time, browser-based) ───────────────────────
echo ""
if [ -f "$CF_DIR/cert.pem" ]; then
    echo -e "${GREEN}✅  Already logged in to Cloudflare (cert.pem found)${NC}"
else
    echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BOLD}  STEP: Log in to Cloudflare${NC}"
    echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
    echo "  Your browser will open to Cloudflare's login page."
    echo "  Sign in and select goldhealthsys.com when asked."
    echo "  Come back here when it says 'You have successfully logged in.'"
    echo ""
    read -p "  Press ENTER when ready to open the browser login..."
    cloudflared tunnel login
    echo -e "${GREEN}✅  Logged in to Cloudflare${NC}"
fi

# ── Step 3: Create the tunnel (idempotent) ───────────────────────────────────
echo ""
echo -e "${BLUE}🔧  Setting up tunnel '${TUNNEL_NAME}'...${NC}"

TUNNEL_ID=""
# Check if tunnel already exists
if cloudflared tunnel list 2>/dev/null | grep -q "$TUNNEL_NAME"; then
    echo -e "${GREEN}✅  Tunnel '${TUNNEL_NAME}' already exists${NC}"
    TUNNEL_ID=$(cloudflared tunnel list 2>/dev/null | grep "$TUNNEL_NAME" | awk '{print $1}')
else
    echo "    Creating tunnel..."
    cloudflared tunnel create "$TUNNEL_NAME"
    TUNNEL_ID=$(cloudflared tunnel list 2>/dev/null | grep "$TUNNEL_NAME" | awk '{print $1}')
    echo -e "${GREEN}✅  Tunnel created — ID: ${TUNNEL_ID}${NC}"
fi

# Find credentials file
CREDS_FILE=$(ls "$CF_DIR/${TUNNEL_ID}.json" 2>/dev/null || ls "$CF_DIR"/*.json 2>/dev/null | head -1 || echo "")
if [ -z "$CREDS_FILE" ]; then
    echo -e "${RED}❌  Could not find tunnel credentials file in $CF_DIR${NC}"
    echo "    Try running: cloudflared tunnel create $TUNNEL_NAME"
    exit 1
fi

# ── Step 4: Write tunnel config ───────────────────────────────────────────────
echo ""
echo -e "${BLUE}📝  Writing tunnel config...${NC}"

cat > "$CONFIG_FILE" <<EOF
# REX Dashboard — Cloudflare Tunnel Config
# Generated by setup_cloudflare_tunnel.sh
# Tunnel: ${TUNNEL_NAME} (${TUNNEL_ID})
#
# Security posture:
#   - TLS termination handled by Cloudflare (HTTPS enforced at edge)
#   - Connection from Cloudflare edge → Mac is encrypted via tunnel (no open ports)
#   - noTLSVerify: false = cloudflared validates the tunnel connection
#   - keepAliveTimeout: connection recycled to prevent stale sessions
#   - Timeouts are tight to prevent slow-loris style attacks

tunnel: ${TUNNEL_ID}
credentials-file: ${CREDS_FILE}

# Logging
loglevel: info
logfile: ${LOG_DIR}/cloudflare-tunnel.log

ingress:
  # Root domain → REX dashboard
  - hostname: ${DOMAIN}
    service: ${LOCAL_URL}
    originRequest:
      connectTimeout: 10s
      tlsTimeout: 10s
      tcpKeepAlive: 30s
      keepAliveTimeout: 90s
      keepAliveConnections: 10
      noTLSVerify: false
      httpHostHeader: ${DOMAIN}
      originServerName: ${DOMAIN}
      disableChunkedEncoding: false

  # www subdomain → same dashboard
  - hostname: www.${DOMAIN}
    service: ${LOCAL_URL}
    originRequest:
      connectTimeout: 10s
      tlsTimeout: 10s
      tcpKeepAlive: 30s
      keepAliveTimeout: 90s
      keepAliveConnections: 10
      noTLSVerify: false
      httpHostHeader: ${DOMAIN}
      originServerName: ${DOMAIN}

  # Catch-all: reject everything else with 404 (do not expose other services)
  - service: http_status:404
EOF

echo -e "${GREEN}✅  Config written: ${CONFIG_FILE}${NC}"

# ── Step 5: Add DNS routes ────────────────────────────────────────────────────
echo ""
echo -e "${BLUE}🌐  Configuring DNS for ${DOMAIN}...${NC}"

cloudflared tunnel route dns "$TUNNEL_NAME" "$DOMAIN" 2>/dev/null && \
    echo -e "${GREEN}✅  DNS: ${DOMAIN} → tunnel${NC}" || \
    echo -e "${YELLOW}⚠   DNS for ${DOMAIN} may already exist — continuing${NC}"

cloudflared tunnel route dns "$TUNNEL_NAME" "www.${DOMAIN}" 2>/dev/null && \
    echo -e "${GREEN}✅  DNS: www.${DOMAIN} → tunnel${NC}" || \
    echo -e "${YELLOW}⚠   DNS for www.${DOMAIN} may already exist — continuing${NC}"

# ── Step 6: Install launchd daemon ────────────────────────────────────────────
echo ""
echo -e "${BLUE}🔁  Installing tunnel auto-start daemon...${NC}"

# Unload existing if present
if launchctl list 2>/dev/null | grep -q "$PLIST_NAME"; then
    launchctl unload "$PLIST_DST" 2>/dev/null || true
fi

CF_BIN=$(which cloudflared)

cat > "$PLIST_DST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${PLIST_NAME}</string>

    <key>ProgramArguments</key>
    <array>
        <string>${CF_BIN}</string>
        <string>tunnel</string>
        <string>--config</string>
        <string>${CONFIG_FILE}</string>
        <string>run</string>
    </array>

    <!-- Start on login, restart if it crashes -->
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>

    <!-- Logs -->
    <key>StandardOutPath</key>
    <string>${LOG_DIR}/cloudflare-tunnel.log</string>
    <key>StandardErrorPath</key>
    <string>${LOG_DIR}/cloudflare-tunnel-err.log</string>

    <!-- Throttle restarts -->
    <key>ThrottleInterval</key>
    <integer>10</integer>
</dict>
</plist>
EOF

launchctl load "$PLIST_DST"
echo -e "${GREEN}✅  Tunnel daemon installed and started${NC}"

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}${BOLD}║   ✅  Setup complete!                            ║${NC}"
echo -e "${GREEN}${BOLD}╚══════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  🌐  Your dashboard is live at:"
echo -e "      ${BOLD}https://${DOMAIN}${NC}"
echo -e "      ${BOLD}https://www.${DOMAIN}${NC}"
echo ""
echo -e "  📋  What's running:"
echo -e "      • Cloudflare Tunnel → ${LOCAL_URL}"
echo -e "      • Auto-starts on Mac login (no port forwarding needed)"
echo -e "      • HTTPS certificate handled by Cloudflare automatically"
echo ""
echo -e "  📂  Logs:"
echo -e "      ${LOG_DIR}/cloudflare-tunnel.log"
echo ""
echo -e "  🔧  Useful commands:"
echo -e "      Check status:  launchctl list | grep cloudflare"
echo -e "      Stop tunnel:   launchctl unload ~/Library/LaunchAgents/${PLIST_NAME}.plist"
echo -e "      Start tunnel:  launchctl load ~/Library/LaunchAgents/${PLIST_NAME}.plist"
echo -e "      Watch logs:    tail -f ${LOG_DIR}/cloudflare-tunnel.log"
echo ""
echo -e "  ⚠️   IMPORTANT: Make sure REX is running before visiting the site."
echo -e "      Start REX:    bash ~/Desktop/REX/run.sh"
echo ""
